events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        location / {
            root /app;
            index index.html;
            # This line fixes the 403/404 routing error by dropping the $uri/ directory fallback
            try_files $uri /index.html; 
        }
    }
}